name: Action JS Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: run hello action
        id: hello-action
        #run: node index.js
        uses: negabaro/action-js-hello-world@master
        with:
          hello-text: 'Hello'
        env:
          HELLO_ENV: 'Hello'
          HELLO_SECRET: ${{secrets.HELLO_SECRET}}
      - name: Get the output arrayResponse
        run: echo "arrayResponse | ${{ steps.hello-action.outputs.arrayResponse }}"
      - name: Get the output textResponse
        run: echo "textResponse | ${{ steps.hello-action.outputs.textResponse }}"
      - name: Get the output envResponse
        run: echo "envResponse | ${{ steps.hello-action.outputs.envResponse }}"
      - name: Get the output secretResponse
        run: echo "secretResponse | ${{ steps.hello-action.outputs.secretResponse }}"